Updates to Fetch and Parse Remote VCEK cert and compare TCB Versions
microsoft/archived-confidential-sidecar-containers pull request #24
Opened 2023-04-06 17:36 UTC by hgarvison

2023-04-06 22:44 UTC, KenGordon commented
Can you not check that this field https://github.com/microsoft/confidential-sidecar-containers/blob/c85bfab6cdea1245e7a6ce84eeec81386b5c3fe5/pkg/common/info.go#L36 as discussed here https://learn.microsoft.com/en-us/azure/security/fundamentals/trusted-hardware-identity-management rather than having to parse the certs? 

Given you start with a known version, then must fetch a given version at all times you can maintain the tcb you have without parsing the cert.

Note also that the remote cache is not the same as the LO THIM cache, thus we need to know the type of endpoint. This model is in place in the previous CertCache which I would like you to extend for this purpose. Have it able to go to an L0 proxy, so move that THIMtoPEM function into the cache code and enable a new type THIM that expects that format. Keep the code that can handle both AMD and Azure endpoints (ir this you are calling THIM but is the non box local but azure local cache. Please note that the L0 and that cache are different.

2023-04-06 22:49 UTC, KenGordon commented
Stavros’s CertCache that you should extend https://github.com/microsoft/confidential-sidecar-containers/blob/84d73d2d2daf910e92cb8d3fe7d9b028aa48e7c6/pkg/attest/certcache.go

To match please reinstate

https://github.com/microsoft/confidential-sidecar-containers/blob/84d73d2d2daf910e92cb8d3fe7d9b028aa48e7c6/cmd/skr/main.go#L30

To let clients specify the fallback end point. Note that that includes the type of the endpoint as they all work differently.

2023-04-06 22:52 UTC, KenGordon commented
If we were being very clever we’d either allow the client to specify several fallbacks, or fallback to the (initially unavailable) L1 proxy to the L0 THIM.

2023-04-07 05:50 UTC, KenGordon commented on cmd/remotefs/azurefs.go
> +	EncodedUvmInformation, err = common.GetUvmInformation()
Oops.

2023-04-07 05:50 UTC, KenGordon commented on pkg/common/info.go
> +		return 0, err
I don’t think we need/should do this. Instead remember the TCB of the certs you have - THIM tells you, all the other sources you have to specify when requesting them.

2023-04-07 05:50 UTC, KenGordon commented on pkg/common/info.go
> +	encodedUvmInformation.RemoteTHIMServiceURL = os.Getenv("UVM_THIM_SERVICE_URL") + "/vcek/v1/"
This is user config, not a system thing. It needs to be parsed out of the json “AzureInformation” as per https://github.com/microsoft/confidential-sidecar-containers/blob/c85bfab6cdea1245e7a6ce84eeec81386b5c3fe5/cmd/skr/main.go#L289

2023-04-07 05:50 UTC, KenGordon commented on pkg/common/info.go
> +func GetUvmInformation() (UvmInformation, error) {
The ContainerPlat people would insist fixing my typo go in a discrete PR. :)

2023-04-07 13:50 UTC, BryceDFisher commented on pkg/common/info.go
> +func GetUvmInformation() (UvmInformation, error) {
An API purist would insist that this is part of the external (to the package) API and thus can never be fixed (laugh)

2023-04-07 14:19 UTC, BryceDFisher commented on pkg/common/info.go
> +			tcbValues[7] = ext.Value[2]
If this stays, the index values need to be turned into constant vars so that they can be reused and future devs can know what is going where.

2023-04-07 14:19 UTC, BryceDFisher commented on pkg/common/info.go
> +			u.RemoteTHIMServiceURL += string(ext.Value) + "/"
This function will only work once.  If it is ever executed a second time, this url will include the host, path, and query string twice.  I recommend building the URL using the url.URL object in the `UvmInformation` type and then set the Path and RawQuery attributes in this function.  When needed, call url.String() to get the final version for querying.

2023-04-07 14:19 UTC, BryceDFisher commented on pkg/attest/attest_test.go
> +		CertChain:               "-----BEGIN CERTIFICATE-----\nMIIFTDCCAvugAwIBAgIBADBGBgkqhkiG9w0BAQowOaAPMA0GCWCGSAFlAwQCAgUA\noRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAgUAogMCATCjAwIBATB7MRQwEgYD\nVQQLDAtFbm
If its easier, you can use the "`" character to do multiline strings.

2023-04-07 14:19 UTC, BryceDFisher commented on pkg/common/info.go
> +			bl = fmt.Sprintf("blSPL=%d", ext.Value[2])
2nd byte of the pkix extension? This is throwing me off.  Could use a comment in here as to why.

2023-04-10 13:14 UTC, hgarvison commented on pkg/common/info.go
> +			u.RemoteTHIMServiceURL += string(ext.Value) + "/"
I actually started it using the url package, in particular the parameters list didn't format correctly to match the url that I saw in the test code, so I switch it to this method. I can attempt it again.

2023-04-10 13:14 UTC, hgarvison commented on pkg/attest/attest_test.go
> +		CertChain:               "-----BEGIN CERTIFICATE-----\nMIIFTDCCAvugAwIBAgIBADBGBgkqhkiG9w0BAQowOaAPMA0GCWCGSAFlAwQCAgUA\noRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAgUAogMCATCjAwIBATB7MRQwEgYD\nVQQLDAtFbm
I just copied this cert chain from already existing test code, which had the string in one line.

2023-04-10 13:31 UTC, hgarvison commented on pkg/common/info.go
> +	encodedUvmInformation.RemoteTHIMServiceURL = os.Getenv("UVM_THIM_SERVICE_URL") + "/vcek/v1/"
I was told that there would be an env var (in the future?), which is why this was created, but if this should be parsed out of the AzureInformation, does that mean a new field is being added to that struct, if so, is there a name for the json field to match that I should know about?

2023-04-10 14:55 UTC, hgarvison commented on pkg/common/info.go
> +			u.RemoteTHIMServiceURL += string(ext.Value) + "/"
@BryceDFisher can you look at the comment I added to the bottom of this function and tell me if that matters or if there's a workaround for that weird string formatting?

2023-04-10 15:25 UTC, KenGordon commented on pkg/common/info.go
> +	encodedUvmInformation.RemoteTHIMServiceURL = os.Getenv("UVM_THIM_SERVICE_URL") + "/vcek/v1/"
These sidecars receive config as base64 encoded json structures (AzureInformation for example) and from the UVM by some means (my PR changes that from env variables to files). You should be reinstating the field in AzureInformation that describes how to find the certs. You should not add that to UvmInformation as it is config about the outside world, provided to the container by “not the UVM”. Yes, today the certs are there as they came from the UVM, but your work is to add an EXTRA source of certs.

2023-04-10 17:51 UTC, BryceDFisher commented on pkg/common/info.go
> +			u.RemoteTHIMServiceURL.Path += string(ext.Value) + "/"
This has the same problem as before.  If this function get's called twice, the value of `u.RemoteTHIMServiceURL.Path` will get appended to twice.

2023-04-10 17:51 UTC, hgarvison commented on pkg/common/info.go
> +			u.RemoteTHIMServiceURL.Path += string(ext.Value) + "/"
This is out of date now

2023-04-10 17:53 UTC, BryceDFisher commented on pkg/common/info.go
>  		if strings.Contains(ext.Id.String(), "1.3.6.1.4.1.3704.1.3.8") {
Just noticed, these can all be `} else if {...` instead of checking the value each time.  You can also switch to a 
`switch ext.Id.String() {
case "1.3.6.1.4.1.3704.1.3.8":
...
`
instead to only evaluate the `.String()` function once.

2023-04-10 18:23 UTC, BryceDFisher commented on cmd/skr/main.go
> +	if ServerCertCache.Endpoint != "" {
We want to include the MAA endpoint if a URL is configured or if the CertChain is present via other means (like the file mounted from the UVM)

2023-04-10 18:25 UTC, BryceDFisher commented on pkg/attest/attest.go
> +		return "", errors.Wrap(err, "converting TCBM string to uint64 failed")
"Unable to convert TCBM from THIM certificates to a uint64"?

2023-04-10 18:28 UTC, BryceDFisher commented on pkg/attest/certcache.go
> +		uri = fmt.Sprintf(AmdTHIMRequestURITemplate, certCache.Endpoint, certCache.TEEType, chipID, reportedTCBBytes[7], reportedTCBBytes[6], reportedTCBBytes[1], reportedTCBBytes[0])
It would still be a good idea to make the indexes constants to aid future development.

2023-04-10 18:31 UTC, BryceDFisher commented on pkg/attest/certcache.go
> +		fullCertChain = append(fullCertChain, []byte(thimCerts.CertificateChain)[:]...)
Probably not a huge issue here, but you can avoid additional memory allocations by either directly allocating the memory up front.

Most memory efficient but does a copy twice:

```go
fullCertChain := make([]byte,0,len(thimCerts.VcekCert)+len(thimCerts.CertificateChain))
```

or make the `fullCertChain` in 1 step, but over allocates memory:

```go
fullCertChain := append([]byte(thimCerts.VcekCert), []byte(thimCerts.CertificateChain)...)
```

2023-04-10 18:36 UTC, BryceDFisher commented on pkg/attest/certcache.go
> +		fullCertChain = append(fullCertChain, []byte(thimCerts.CertificateChain)[:]...)
https://go.dev/play/p/PNr6XOZIc92

2023-04-10 18:43 UTC, BryceDFisher commented on cmd/skr/main.go
> +	if ServerCertCache.Endpoint != "" {
```go
if serverCertCache.Endpoint != "" || encodedUvmInformation.CertChain != "" {
```

2023-04-10 19:03 UTC, BryceDFisher approved these changes

2023-04-11 09:59 UTC, KenGordon commented on pkg/common/info.go
> -	certsString := certsFromTHIM.VcekCert + certsFromTHIM.CertificateChain
This line, which you have moved out to the caller someplace. Is the main point of this function

2023-04-11 09:59 UTC, KenGordon commented on pkg/common/info.go
> +func THIMtoPEM(encodedHostCertsFromTHIM string) (THIMCerts, error) {
This function is supposed to return a PEM, hence the name.

2023-04-11 12:28 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
Is this the L0/L1 THIM or an Azure Cache? If it is the L0/L1 THIM then it doesn't match the request form here https://dev.azure.com/msazure/ContainerPlatform/_git/containerd.cri?path=/pkg/containerd/opts/spec.go&version=GBmain&line=31&lineEnd=32&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents and if it is an Azure cache then the code is surely already in the else case below (was line 80, now line 115)

2023-04-11 13:35 UTC, hgarvison commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
I was informed that the THIM endpoint would match the format in the AMD documentation https://www.amd.com/system/files/TechDocs/57230.pdf hence the extra conditional, if that's not the case, I can update the the request form to match that format.

2023-04-11 16:13 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
That is the AMD endpoints. The local THIM ones are not the same. The certs ect are as described but not the json. Try this sort of request

curl GET "http://169.254.169.254/metadata/THIM/amd/certification" -H "Metadata: true” and compare it with replies from the AMD one.

2023-04-11 16:13 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
(Note that the AMD endpoints are case sensitive)

2023-04-11 16:23 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
Basically there are four sources and three formats for the cert infomation:
 - AMD servers (probably throttled) - you need to ask by TCB
 - Azure Cache - you need to ask by TCB
 - Local THIM endpoint - returns current (at time of asking - there is still a race) TCB
 - UVM/hcsshim provided THIM certs - returns TCB of container startup time. These are the same certs at the Local endpoint, just fetched by hcsshim.

2023-04-11 16:58 UTC, hgarvison commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
Based on this, are you recommending that I update the retrieveCertChain function to get the TCB from the local THIM endpoint and then parse/use that value to get the certChain (as it was doing before my edits)? Or are you suggesting that I make a separate function to get the tcb value from the local THIM endpoint and call that whenever we need to update/compare the TCB value with the one in the SNP report?

2023-04-11 17:04 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
You should only ever obtain the TCB from an attestation report. I am just telling you the properties of the THIM ones. Given you have a TCB from a report and it does not match you need to fetch a fresh set of certs, either from the live local THIM (and you will need to check the TCB matches and maybe get a new report if it does not) or from a remote one (From AzCache or AMD) using the TCB in the report to specify what one you need. The AzCache and AMD versions of that fetching are in Stavros's original CertCache code.

2023-04-11 17:07 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
For the local and fetched by hcsshim certs you have two races. One between obtaining the certs and getting the report and another between getting the report and obtaining the local certs. You should probably always get the certs first and retry BOTH the cert fetch and the report fetch if the certs do not match the report.

2023-04-12 15:12 UTC, hgarvison commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
So I think I've addressed the snp/cache tcb checks, but I still need clarification on when to use the local THIM endpoint to refresh the cert cache. Thanks!

2023-04-12 16:32 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
When the AzureInformation that provides the endpoints provides one of the (local) THIM type.

2023-04-13 13:20 UTC, hgarvison commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
What I meant was, how is the application supposed to know if the endpoint provided is a local THIM type? Is the flag I made in CertCache struct acceptable or is there another method that will provide this?

2023-04-13 15:10 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
That is what this is for I think 
	TEEType    string `json:"tee_type,omitempty"`

2023-04-13 15:17 UTC, hgarvison commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
What would be the value of TEEType that would indicate THIM? "THIM"?

2023-04-13 15:23 UTC, KenGordon commented on pkg/attest/certcache.go
> +	} else if certCache.THIM {
I might call it LocalTHIM. Shiv's team call the thing we call the Azure Cache THIM I believe.

2023-04-14 12:01 UTC, svolos requested changes

2023-04-14 12:01 UTC, svolos commented on examples/skr/importkeyconfig.json
> +            "endpoint": "<microsoft-azure-attestation-endpoint>"
the authority can be any entity; not just an MAA instance. Please fix to <authority-of-claims-required-for-key-release-from-key-vault>

2023-04-14 12:01 UTC, svolos commented on pkg/attest/attest.go
> +	if _, err := os.Stat("/dev/sev"); os.IsNotExist(err) {
@KenGordon , i just realized that this line needs to change and check whether any of the /dev/sev or /dev/sev-guest exists.

2023-04-14 12:01 UTC, svolos commented on pkg/attest/attest.go
>  	/* TODO: to support use outside of Azure add code to fetch the AMD certs here */
i guess this comment needs to go away because this PR does exactly what the TODO says.

2023-04-14 12:01 UTC, svolos commented on pkg/attest/certcache.go
> -func (certCache CertCache) retrieveCertChain(chipID string, reportedTCB uint64) ([]byte, error) {
What is the purpose of the string return variable? Can you update the retrieveCertChain description to explain what the return values are? []byte is the full cert chain and string is related to thim ?

2023-04-14 13:16 UTC, KenGordon commented on pkg/attest/attest.go
> +	if _, err := os.Stat("/dev/sev"); os.IsNotExist(err) {
Good point.

2023-04-14 13:19 UTC, KenGordon commented on pkg/attest/certcache.go
> +	LocalTHIMCertEndpoint            = "http://169.254.169.254/metadata/THIM/amd/certification"
This needs to come as config, same as the others. Since the L1 version is yet to be defined I'd assume the whole path is must be supplied.

2023-04-14 13:26 UTC, KenGordon commented on pkg/common/info.go
> +	ThimTcbm                uint64 // TCBM for the particular UVM image
UVM images do not have a TCBM. That is a property of the report and the certs.

2023-04-14 13:26 UTC, KenGordon commented on pkg/common/info.go
> +		thimTcbm, err := strconv.ParseUint(tcbmFromTHIM, 10, 64)
you might move extracting the tcb into THIMtoPEM and call that something like decodeTHIM. bIn the case you fetch a THIM though it will be plain json, not base64 encoded I believe.

2023-04-14 13:57 UTC, hgarvison commented on pkg/attest/certcache.go
> +	LocalTHIMCertEndpoint            = "http://169.254.169.254/metadata/THIM/amd/certification"
And where in the config would that be supplied? The encodedHostCertsFromTHIM (demarshalled into the THIMCerts struct)?

2023-04-19 15:51 UTC, KenGordon commented on .gitignore
> +/tools/get-snp-report/*
There is code there.

2023-04-19 15:58 UTC, KenGordon commented on tools/get-snp-report/verbose-report.c
> +    if (supportsDevSev())
Please don't. :)

2023-04-19 16:01 UTC, KenGordon commented on Dockerfile.skr
> +FROM golang:latest as build
This doesn't belong here following how Stavros built the repo. It is fine as it is in anycase I believe.

2023-04-19 16:01 UTC, hgarvison commented on tools/get-snp-report/verbose-report.c
> +    if (supportsDevSev())
Ah, my vscode auto-formatted this. I can revert it.

2023-04-19 16:29 UTC, svolos requested changes
How is this new functionality being tested? That means, how can we check the following scenarios: 
(A) If cert chain is stale, the cert chain is retrieved from local THIM
(B) If cert chain is stale, the cert chain is retrieved from local cert cache.

2023-04-19 16:29 UTC, svolos commented on Dockerfile.skr
> +FROM golang:latest as build
Are these changes to the Dockerfile.skr consistent with the version of the build.sh ? What's the reasoning behind this change?

2023-04-19 16:29 UTC, svolos commented on tools/securitypolicydigest/main.go
>  	flag.StringVar(&filename, "f", "", "file containing security policy in base64-encoded string format")
merge conflict resolution issue here

2023-04-19 16:29 UTC, svolos commented on pkg/attest/certcache.go
> +	} else if certCache.TEEType == "LocalTHIM" && localThimUri != "" {
I am quite confused regarding the cert cache endpoints and the order at which they are called.

There is the CertChain as part of the uvmInformation which may be stale and hence will require refreshing the cert chain via a cert cache endpoint: local THIM endpoint or a remote cert cache. The remote cert cache may be the Azure Cert Cache or the AMD Cert Cache as denoted by the certCache.AMD flag.

What is the desired priority of the cert cache endpoints? is it local THIM followed by remote cert cache ? or is it remote cert cache followed by local THIM ?  I would expect that the local THIM should be called first.  The current if-then-else statement prioritizes AMD cert cache endpoints over local THIM endpoints, and prioritizes local THIM endpoints over Azure Cert cache endpoints. So, this needs to change based on the desired priority. 

Another issue here is how the code decides whether the local THIM shall be used. Right now, the TEEtype is re-used to pass information whether the LocalTHIM shall be used or not. This is problematic because in the scenario that the remote cache needs to be called, the TEE type will not have the right value (e.g., SevSnpVm.) (For instance, if this  TEEType is set to LocalTHIM when the certcache instance is brought up by the cmd/skr/main.go, then fetching certs from AMD or Azure cert cache will fail due to non-correct TEEType. If the TEEType is set to SevSnpVm, the local thim endpoint will never be called)

The confusion here is made because the CertCache object (initially meant to capture remote cache endpoint information) is being reused for local cert cache endpoint. 

[Less hassle option] One option is to remove local cert cache endpoint functionality from the CertCache:
- I would remove the code block about LocalTHIM calls here and keep the certcache implementation and API as it used to be. 
- The right place to call the local thim shall be in the attest.RefreshCertChain(...., localTHIM = true) . If localTHIM, use the uvmInformation.localThimUri to call using the code 89-102. 
- The attest function shall implement the desired priority by calling attest.RefresthCertChain( ...., true) and checking if the cert chain tcb matches the report's and if not by calling attest.RefresthCertChain( ...., false) which will call the certCache.RetrieveCertChain 

[Preferred option] Another option is to re-visit the CertCache object and have the notion of a LocalTHIM Object (will cotnain the uri), a RemoteCache Object  (will contain all the existing attributes) and a LocalTHIMPriority flag. Then we have LocalTHIMGetCertChain and RemoteCetCertChain methods to remove the implementation of the priority in the current GetCertChain method. The priority (as discussed above) will be implemented by the attest.RefreshCertChain method based on the priority flag specified in the CertCache object.

2023-04-19 16:30 UTC, KenGordon commented on pkg/attest/attest.go
> +	if _, err := os.Stat("/dev/sev"); errors.Is(err, os.ErrNotExist) {
Oh yes, maybe I should do that on main in anycase. Opps.

2023-04-19 17:43 UTC, hgarvison commented on pkg/attest/certcache.go
> +	} else if certCache.TEEType == "LocalTHIM" && localThimUri != "" {
I'm okay with the less hassle option.

2023-04-21 13:41 UTC, KenGordon commented on pkg/attest/certcache.go
> +	EndpointType string `json:"endpoint_type,omitempty"` // AMD, AzCache, LocalTHIM
I think that the endpoint_type is now required and if the whole thing is missing we should not try to fetch a cert but instead fail with some message about the stale certs. When I ran this container with my last test arm template if fails like this:
root@SandboxHost-638176805756747558:/# cat keyrelease.out 
{"error":"attestation failed: refreshing CertChain failed: HTTP GET failed: Get \"https:////certificates/c5943d9ba2f4837a343b079cc7b65d5669d2967caff818bf4ebc8429fd32d04b782c7cd032971aa0dda2892842d9f59d93a381c0eb47d62d75bb17fdb22cc271/7308000000000003?\": http: no Host in request URL"}root@SandboxHost-638176805756747558:/#

2023-04-21 13:47 UTC, KenGordon commented on pkg/attest/certcache.go
> +	default: // case "AzCache": --> to match previous if-else logic and avoid failing when no certcache is supplied
As per other comment, if we have not CertCache we have no idea where to send the request. We should not try. The previous logic might have had this problem to, but it always had to have a url as it was how it was done 100% of the time, not just a fallback.

2023-04-21 13:49 UTC, KenGordon commented on pkg/attest/certcache.go
>  type CertCache struct {
Can we give this (and the file) a new name please? I know this was always called CertCache, but now it is more like a CertFetcher and the thing above caches the result. The previous naming was about the AzCache that this talks to.

2023-04-25 10:24 UTC, svolos requested changes
I apologize for not suggesting this yesterday, but I thought a bit more about the corruptedTCB testing process.

Now that we tested all the paths, we should remove the TCB corruption ability via the skr.sh. So, rather than passing it via the skr.sh (or via an env. variable), we can add a var in line 23-27 

	// for testing mis-matched TCB versions allowTestingWithMismatchedTCB 
	// and MismatchedTCB 
        var allowTestingWithMismatchedTCB = false
	var MismatchedTCB = "ffffffff"

then in your code, you can check if the allowTestingWithMismatchedTCB is true, then use the MismatchedTCB as a value for the Tcbm. Optionally we can pass a allowTestingWithMismatchedTCB flag (as opposed to the corrupted value) via the skr.sh to the binary that overrides the allowTestingWithMismatchedTCB. (In essence, rename the current CorruptedTcbm variable to allowTestingWithMismatchedTCB variable and modify the codebase to expect this as a boolean flag)

2023-04-25 14:27 UTC, KenGordon commented
> I apologize for not suggesting this yesterday, but I thought a bit more about the corruptedTCB testing process.
> 
> We should remove the TCB corruption ability via the skr.sh. So, rather than passing it via the skr.sh (or via an env. variable), we can add a var in line 23-27
> 
> ```
> // for testing mis-matched TCB versions allowTestingWithMismatchedTCB 
> // and MismatchedTCB 
>     var allowTestingWithMismatchedTCB = false
> var MismatchedTCB = "ffffffff"
> ```
> 
> then in your code, you can check if the allowTestingWithMismatchedTCB is true, then use the MismatchedTCB as a value for the Tcbm.
> 
> Finally, we can introduce an skr_test.sh script (variation of the current skr.sh) that passes an allowTestingWithMismatchedTCB flag (as opposed to the corrupted value) to the binary that overrides the allowTestingWithMismatchedTCB. (In essence, rename the current CorruptedTcbm variable to allowTestingWithMismatchedTCB variable and modify the codebase to expect this as a boolean flag)
> 
> This way, the skr.sh (production entry point) will not have means to test while the skr_test.sh will have means to test. Then, we will need to add skr_test.sh to the container image.
> 
> @KenGordon thoughts on this?

yes, having a different script that lets an arm template very obviously control that it is testing a thing seems better.

2023-04-25 15:36 UTC, svolos approved these changes

2023-04-25 15:38 UTC, merged