Check for sev-guest dev (6.1)
microsoft/archived-confidential-sidecar-containers pull request #28
Opened 2023-04-24 15:56 UTC by KenGordon

The PSP device is exposed as /dev/sev-guest rather than /dev/sev. When determining whether this is a real SNP box we need to check both. If not a real SNP box then a fake report is generated to allow for testing and development.

2023-04-24 16:04 UTC, hgarvison commented on pkg/attest/attest.go
> +	if _, err := os.Stat("/dev/sev"); errors.Is(err, os.ErrNotExist) {
This check should be added to the RawAttest function as well

2023-04-24 16:06 UTC, svolos commented on pkg/attest/attest.go
> +	if _, err := os.Stat("/dev/sev"); errors.Is(err, os.ErrNotExist) {
Good catch.

2023-04-25 08:43 UTC, svolos requested changes
RawAttest requires the same check as Attest

2023-04-25 08:54 UTC, KenGordon commented on pkg/attest/attest.go
> +	if _, err := os.Stat("/dev/sev"); errors.Is(err, os.ErrNotExist) {
Done

2023-04-25 13:10 UTC, hgarvison approved these changes

2023-04-25 15:32 UTC, svolos approved these changes

2023-04-25 15:43 UTC, svolos commented
These changes have been already merged as part of PR #24

2023-04-25 15:43 UTC, closed without merging